Add a single status check for all matrix jobs

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -15,7 +15,6 @@ on:
 
 jobs:
   run-matrix:
-    name: Run CMake Build and Test Matrix
     uses: ./.github/workflows/cmake_build_and_test.yml
     strategy:
       # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
@@ -108,3 +107,17 @@ jobs:
       head_ref: ${{ github.event.pull_request.head.ref }}
       base_ref: ${{ github.event.pull_request.base.ref }}
     secrets: inherit
+  status_check:
+    runs-on: ubuntu-latest
+    needs: run-matrix
+    if: ${{ always() }}
+    steps:
+      - name: Check for failed jobs
+        shell: bash
+        run: |
+          if [ -n "${{ needs.run-matrix.result }}" != "success" ]; then
+            echo "Some jobs failed. Please check the logs."
+            exit 1
+          else
+            echo "All jobs completed successfully."
+          fi
